### PR TITLE
Update builds.go

### PR DESCRIPTION
**Pull request by Rchardon**

### CODE REVIEW

**Comment by Zamiell** [comment]
can you provide justification for why you are removing some antisynergies?

**Comment by Rchardon** [comment]
Where, here or in the file ?

**Comment by Zamiell** [comment]
here

**Comment by Rchardon** [comment]
Cricket's body : 
Works with Cain and Samson since the range stat was reworked in Rep
It's still a tears up on both azazels and split tears are useful

Dead Eye - Lilith : 
While it is harder to aim than any other character, it still works

Ipecac - Azazel : 
Low chances to hit yourself now, i think it was reworked in a patch

Incubus x2 - Forgotten : 
If you place the incubuses correctly it works

Eye of the occult - Both Azazels : 
It literally synergizes

**Comment by Zamiell** [comment]
> It's still a tears up on both azazels and split tears are useful

i playtested it and it seems garbage

**Comment by Zamiell** [comment]
> While it is harder to aim than any other character, it still works

its not fun whatsoever

**Comment by Zamiell** [comment]
> Low chances to hit yourself now, i think it was reworked in a patch

i playtested it and it is cancer to play

**Comment by Zamiell** [comment]
> If you place the incubuses correctly it works

did you playtest this? 90% of the time the incubuses aren't placed correctly

**Comment by Rchardon** [comment]
> > If you place the incubuses correctly it works
> 
> did you playtest this? 90% of the time the incubuses aren't placed correctly

You can still throw the bones like you would do anyway

**Comment by Zamiell** [comment]
forgotten is usually played by swinging bones, not throwing bones

**Comment by Rchardon** [comment]
You alternate swinging and throwing because it does more DPS

**Comment by Zamiell** [comment]
yeah but the throws are at melee range so in the context of having the incubus hitting things what you said doesn't apply

**Comment by Zamiell** [comment]
see my edits

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
